export const GET_REQUEST = 'GET_REQUEST'
export const GET_SUCCESS = 'GET_SUCCESS'
export const GET_FAILURE = 'GET_FAILURE'

export const SAVING_REQUEST = 'SAVING_REQUEST'
export const SAVING_SUCCESS = 'SAVING_SUCCESS'
export const SAVING_FAILURE = 'SAVING_FAILURE'

export const DELETING_REQUEST = 'DELETING_REQUEST'
export const DELETING_SUCCESS = 'DELETING_SUCCESS'
export const DELETING_FAILURE = 'DELETING_FAILURE'

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const VERIFY_REQUEST = "VERIFY_REQUEST";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";